version: '3'
services:
  # Create a bookmark bot instance
  bookmark:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      TOKEN: ${TOKEN}
      STATUS: DEVELOPMENT
      GUILD_ID: 973562496763953200
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin
    restart: always
    networks:
      - bookmark_network
  # Create mongodb instance
  mongodb:
    environment:
      #   Credentials bellow are used to login to the database, 
      #   if you change these make sure to also update the link up above
      #   (mongodb://admin:root@mongodb:27017/bookmark?authSource=admin)
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    image: "mongo:latest"
    restart: always
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - bookmark_network
volumes:
  mongodb_data_container:
    driver: local
networks:
  bookmark_network:
    driver: bridge
