version: '3'
services: 
  bot: 
    build: https://raw.githubusercontent.com/Nidrux/Bookmark/main/app/Dockerfile
    depends_on: 
      - mongodb
    environment: 
      - TOKEN=
      - STATUS=DEVELOPMENT
      - GUILD_ID=973562496763953152
      - MONGODB_URI=mongodb://admin:root@mongodb:27017/bookmark?authSource=admin
    image: bot
    restart: always
  mongodb: 
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_USERNAME=root
    image: "mongo:latest"
    restart: always
    volumes: 
      - mongodb_data_container:/data/db
volumes: 
  - mongodb_data_container
